# Author: Gonzalo Ramos Zúñiga
# Since: 2023/04/06

Parameters:
  AcmCertificateArn:
    Type: String
  Alias:
    Type: String
  HostedZoneId:
    Type: String

AWSTemplateFormatVersion: 2010-09-09
Resources:
  # S3
  AssetsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketEncryption: # Enable & Amazon S3-managed keys (SSE-S3) selected
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: s3-grz-assets
      ObjectLockEnabled: false
      OwnershipControls: # ACLs disabled (recommended) selected
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration: # Block all public access ticked
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AssetsBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${AssetsDistribution}
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Resource: !Sub ${AssetsBucket.Arn}/*
  # CloudFront
  AssetsDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Join ["", ["assets.", !Ref Alias]]
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          Compress: true
          SmoothStreaming: false
          TargetOriginId: AssetsBucketOriginId
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2and3
        IPV6Enabled: true
        Origins:
          - DomainName: !GetAtt AssetsBucket.DomainName
            Id: AssetsBucketOriginId
            OriginAccessControlId: !GetAtt AssetsDistributionOriginAccessControl.Id
            OriginShield:
              Enabled: true
              OriginShieldRegion: us-east-1
            S3OriginConfig:
              OriginAccessIdentity: ""
        PriceClass: PriceClass_All # Use all edge locations (best performance)
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
  AssetsDistributionOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: cf-oac-assets
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  # Route 53
  AssetsDistributionRecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets: # Z2FDTNDATAQYW2 = Constant for CloudFront aliases
        - AliasTarget:
            DNSName: !GetAtt AssetsDistribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2
          Name: !Join ["", ["assets.", !Ref Alias]]
          Type: A